CREATE TABLE [dbo].[EStopCards] (
    [EStopCardID]          INT            IDENTITY (1, 1) NOT NULL,
    [UserID]               INT            NULL,
    [FirstName]            NVARCHAR (50)  NULL,
    [LastName]             NVARCHAR (50)  NULL,
	[OJ]		           NVARCHAR (50)  NULL,
	[SubOJ]		           NVARCHAR (50)  NULL,
    [DateCreated]          DATETIME       NULL,
    [SigNesigPostupak]     BIT            NOT NULL,
    [NesigRadnjaUvijet]    BIT            NULL,
    [ReakcijaLjudi]        BIT            NULL,
    [Ozo]                  BIT            NULL,
    [polozajLjudi]         BIT            NULL,
    [alatioOprema]         BIT            NULL,
    [ProcedureiUrednosti]  BIT            NULL,
    [PodReak1]             BIT            NULL,
    [PodReak2]             BIT            NULL,
    [PodReak3]             BIT            NULL,
    [PodReak4]             BIT            NULL,
    [PodReak5]             BIT            NULL,
    [PodReak6]             BIT            NULL,
    [PodOzo1]              BIT            NULL,
    [PodOzo2]              BIT            NULL,
    [PodOzo3]              BIT            NULL,
    [PodOzo4]              BIT            NULL,
    [PodOzo5]              BIT            NULL,
    [PodOzo6]              BIT            NULL,
    [PodOzo7]              BIT            NULL,
    [PodPolo1]             BIT            NULL,
    [PodPolo2]             BIT            NULL,
    [PodPolo3]             BIT            NULL,
    [PodPolo4]             BIT            NULL,
    [PodPolo5]             BIT            NULL,
    [PodPolo6]             BIT            NULL,
    [PodPolo7]             BIT            NULL,
    [PodPolo8]             BIT            NULL,
    [PodPolo9]             BIT            NULL,
    [PodPolo10]            BIT            NULL,
    [PodPolo11]            BIT            NULL,
    [PodPolo12]            BIT            NULL,
    [PodAlati1]            BIT            NULL,
    [PodAlati2]            BIT            NULL,
    [PodAlati3]            BIT            NULL,
    [PodProce1]            BIT            NULL,
    [PodProce2]            BIT            NULL,
    [PodProce3]            BIT            NULL,
    [PodProce4]            BIT            NULL,
    [PodProce5]            BIT            NULL,
    [PodProce6]            BIT            NULL,
    [DatumOtvaranja]       DATE           NOT NULL,
    [OpisSukNesuk]         NVARCHAR (255) NOT NULL,
    [KorektivneRadnje]     NVARCHAR (255) NOT NULL,
    [AnalizaUzorka]        NVARCHAR (255) NULL,
    [RokZaRjes]            DATE           NULL,
    [OdgovornaOsoba]       NVARCHAR (50)  NULL,
    [CardStatus]           VARCHAR (20)   NOT NULL,
    [Komentar]             NVARCHAR (255) NULL,
    [DatumZatvaranja]      DATE           NULL,
    [lastModifiedID]       INT            NULL,
    [lastModifiedName]     NVARCHAR (50)  NULL,
    [lastModifiedLastName] NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([EStopCardID] ASC),
    FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID])
);

