//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroscoStopCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class EStopCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EStopCard()
        {
            this.EStopCardsNominations = new HashSet<EStopCardsNomination>();
        }
    
        public int EStopCardID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OJ { get; set; }
        public string SubOJ { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool SigNesigPostupak { get; set; }
        public Nullable<bool> NesigRadnjaUvijet { get; set; }
        public Nullable<bool> ReakcijaLjudi { get; set; }
        public Nullable<bool> Ozo { get; set; }
        public Nullable<bool> polozajLjudi { get; set; }
        public Nullable<bool> alatioOprema { get; set; }
        public Nullable<bool> ProcedureiUrednosti { get; set; }
        public Nullable<bool> PodReak1 { get; set; }
        public Nullable<bool> PodReak2 { get; set; }
        public Nullable<bool> PodReak3 { get; set; }
        public Nullable<bool> PodReak4 { get; set; }
        public Nullable<bool> PodReak5 { get; set; }
        public Nullable<bool> PodReak6 { get; set; }
        public Nullable<bool> PodOzo1 { get; set; }
        public Nullable<bool> PodOzo2 { get; set; }
        public Nullable<bool> PodOzo3 { get; set; }
        public Nullable<bool> PodOzo4 { get; set; }
        public Nullable<bool> PodOzo5 { get; set; }
        public Nullable<bool> PodOzo6 { get; set; }
        public Nullable<bool> PodOzo7 { get; set; }
        public Nullable<bool> PodPolo1 { get; set; }
        public Nullable<bool> PodPolo2 { get; set; }
        public Nullable<bool> PodPolo3 { get; set; }
        public Nullable<bool> PodPolo4 { get; set; }
        public Nullable<bool> PodPolo5 { get; set; }
        public Nullable<bool> PodPolo6 { get; set; }
        public Nullable<bool> PodPolo7 { get; set; }
        public Nullable<bool> PodPolo8 { get; set; }
        public Nullable<bool> PodPolo9 { get; set; }
        public Nullable<bool> PodPolo10 { get; set; }
        public Nullable<bool> PodPolo11 { get; set; }
        public Nullable<bool> PodPolo12 { get; set; }
        public Nullable<bool> PodAlati1 { get; set; }
        public Nullable<bool> PodAlati2 { get; set; }
        public Nullable<bool> PodAlati3 { get; set; }
        public Nullable<bool> PodProce1 { get; set; }
        public Nullable<bool> PodProce2 { get; set; }
        public Nullable<bool> PodProce3 { get; set; }
        public Nullable<bool> PodProce4 { get; set; }
        public Nullable<bool> PodProce5 { get; set; }
        public Nullable<bool> PodProce6 { get; set; }
        public System.DateTime DatumOtvaranja { get; set; }
        public string OpisSukNesuk { get; set; }
        public string KorektivneRadnje { get; set; }
        public string AnalizaUzorka { get; set; }
        public Nullable<System.DateTime> RokZaRjes { get; set; }
        public string OdgovornaOsoba { get; set; }
        public string CardStatus { get; set; }
        public string Komentar { get; set; }
        public Nullable<System.DateTime> DatumZatvaranja { get; set; }
        public Nullable<int> lastModifiedID { get; set; }
        public string lastModifiedName { get; set; }
        public string lastModifiedLastName { get; set; }
        public Nullable<bool> Nominacije { get; set; }
        public Nullable<bool> UziIzbor { get; set; }
        public Nullable<bool> Dobitne { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EStopCardsNomination> EStopCardsNominations { get; set; }
        public virtual User User { get; set; }
    }
}
