//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroscoStopCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class H
    {
        public int HSID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Oj1 { get; set; }
        public string Oj2 { get; set; }
        public string Lokacija { get; set; }
        public string Operatori { get; set; }
        public string Status { get; set; }
        public Nullable<int> ManNoCrosco { get; set; }
        public Nullable<int> ManNoContracori { get; set; }
        public Nullable<int> ManNoThirdParty { get; set; }
        public Nullable<int> SumNo { get; set; }
        public Nullable<int> ManHoursCrosco { get; set; }
        public Nullable<int> ManHoursContracori { get; set; }
        public Nullable<int> ManHoursThirdParty { get; set; }
        public Nullable<int> SumManHours { get; set; }
        public Nullable<int> KMCrosco { get; set; }
        public Nullable<int> KMContracori { get; set; }
        public Nullable<int> KMThirdParty { get; set; }
        public Nullable<int> SumKM { get; set; }
        public Nullable<int> CRoNII { get; set; }
        public Nullable<int> CRoRTI { get; set; }
        public Nullable<int> CRoRTA { get; set; }
        public Nullable<int> CRoNM { get; set; }
        public Nullable<int> CRoFAC { get; set; }
        public Nullable<int> CRoMTC { get; set; }
        public Nullable<int> CRoRWC { get; set; }
        public Nullable<int> CRoLTI { get; set; }
        public Nullable<int> CRoFTL { get; set; }
        public Nullable<int> CRoTRI { get; set; }
        public Nullable<int> ConNII { get; set; }
        public Nullable<int> ConRTI { get; set; }
        public Nullable<int> ConRTA { get; set; }
        public Nullable<int> ConNM { get; set; }
        public Nullable<int> ConFAC { get; set; }
        public Nullable<int> ConMTC { get; set; }
        public Nullable<int> ConRWC { get; set; }
        public Nullable<int> ConLTI { get; set; }
        public Nullable<int> ConFTL { get; set; }
        public Nullable<int> ConTRI { get; set; }
        public Nullable<int> ThrdNII { get; set; }
        public Nullable<int> ThrdRTI { get; set; }
        public Nullable<int> ThrdRTA { get; set; }
        public Nullable<int> ThrdNM { get; set; }
        public Nullable<int> ThrdFAC { get; set; }
        public Nullable<int> ThrdMTC { get; set; }
        public Nullable<int> ThrdRWC { get; set; }
        public Nullable<int> ThrdLTI { get; set; }
        public Nullable<int> ThrdFTL { get; set; }
        public Nullable<int> ThrdTRI { get; set; }
        public Nullable<int> SWA { get; set; }
        public Nullable<int> Alco { get; set; }
        public Nullable<int> TPS { get; set; }
        public Nullable<int> PlinDrill { get; set; }
        public Nullable<int> EvacDrill { get; set; }
        public Nullable<int> BOPDrill { get; set; }
        public Nullable<int> FireDrill { get; set; }
        public Nullable<int> RescueDrill { get; set; }
        public Nullable<int> SpillDrill { get; set; }
        public Nullable<int> OtherDrill { get; set; }
        public string OtherDrillComment { get; set; }
        public Nullable<int> DaysWoLTI { get; set; }
    
        public virtual User User { get; set; }
    }
}
