//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroscoStopCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopCard
    {
        public int StopCardID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool SigNesigPostupak { get; set; }
        public string NesigRadnjaUvijet { get; set; }
        public string ElementProm { get; set; }
        public string PodelementProm { get; set; }
        public Nullable<System.DateTime> DatumOtvaranja { get; set; }
        public string OpisSukNesuk { get; set; }
        public string KorektivneRadnje { get; set; }
        public string AnalizaUzorka { get; set; }
        public Nullable<System.DateTime> RokZaRjes { get; set; }
        public string OdgovornaOsoba { get; set; }
        public string CardStatus { get; set; }
        public string Komentar { get; set; }
        public Nullable<System.DateTime> DatumZatvaranja { get; set; }
    
        public virtual User User { get; set; }
    }
}
