<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StopReports.aspx.cs" Inherits="CroscoStopCard.StopReports" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>
                STOP Analiza
            </h1>
            <asp:Panel ID="StopAnaliza" runat="server" Width="100%" HorizontalAlign="Center">
                <table id="SAtb1">
                    <tr>
                        <th>
                            Podaci
                        </th>
                         <th>
                            Siječanj
                        </th>
                         <th>
                            Veljača
                        </th>
                         <th>
                            Ožujak
                        </th>
                         <th>
                            Q1
                        </th>
                        <th>
                            Travanj
                        </th>
                         <th>
                            Svibanj
                        </th>
                         <th>
                            Lipanj
                        </th>
                         <th>
                            Q2
                        </th>
                        <th>
                            H1
                        </th>
                        <th>
                            Srpanj
                        </th>
                         <th>
                            Kolovoz
                        </th>
                         <th>
                            Rujanj
                        </th>
                         <th>
                            Q3
                        </th>
                        <th>
                            Listopad
                        </th>
                         <th>
                            Studeni
                        </th>
                         <th>
                            Prosinac
                        </th>
                         <th>
                            Q4
                        </th>
                        <th>
                            H2
                        </th>
                        <th>
                            Godina
                        </th>
                    </tr>
                    <tr>
                        <th>
                            Dani rada
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Broj kartica
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Pozitivne kartice
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Negativne kartice
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Nesigurne radnje
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Nesigurne uvjete
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Otvorene kartice
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Kartice u postupku
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Zatvorene kartice
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Zatvorene negativne kartice
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Zatvorene nesigurne radnje
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Zatvorene nesigurne uvjete
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Broj radnika
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Kartice po osobi
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Kartice po osobi po dani rada
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Negativne kartice po osobi
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Negativne kartice po osobi po dani rada
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                </table>
            </asp:Panel>
            <h1>
                Elementi promatranja
            </h1>
            <asp:Panel ID="ElmentiTable" runat="server" Width="100%" HorizontalAlign="Center">
                <table id="ElmentiTable1">

                </table>
            </asp:Panel>

            <h1>
                Podaci o incidentima
            </h1>
            <asp:Panel ID="HStable" runat="server" Width="100%" HorizontalAlign="Center">
                <table id="HStable1">
                    <tr>
                        <th>
                            Podaci
                        </th>
                         <th>
                            Siječanj
                        </th>
                         <th>
                            Veljača
                        </th>
                         <th>
                            Ožujak
                        </th>
                         <th>
                            Q1
                        </th>
                        <th>
                            Travanj
                        </th>
                         <th>
                            Svibanj
                        </th>
                         <th>
                            Lipanj
                        </th>
                         <th>
                            Q2
                        </th>
                        <th>
                            H1
                        </th>
                        <th>
                            Srpanj
                        </th>
                         <th>
                            Kolovoz
                        </th>
                         <th>
                            Rujanj
                        </th>
                         <th>
                            Q3
                        </th>
                        <th>
                            Listopad
                        </th>
                         <th>
                            Studeni
                        </th>
                         <th>
                            Prosinac
                        </th>
                         <th>
                            Q4
                        </th>
                        <th>
                            H2
                        </th>
                        <th>
                            Godina
                        </th>
                    </tr>
                    <tr>
                        <th>
                            Sati rada
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            FTL
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            LTI
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            RWC
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            MTC
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            FAC
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            NM
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            RTA
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            RTI
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            NII
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            SWA
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            TPS
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Broj Alkotestiranja
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            LTIF
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            LTI rate
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            TRIF
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            TRI rate
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            NMF
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                    <tr>
                        <th>
                            NM rate
                        </th>
                        <td>
                            31
                        </td>
                        <td>
                            29
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q1
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q2
                        </td>
                        <td>
                            H1
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            Q3
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            Q4
                        </td>
                        <td>
                            H2
                        </td>
                        <td>
                            Year
                        </td>
                    </tr>
                </table>
            </asp:Panel>
        </div>
    </form>
</body>
</html>
